/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pdoshi' at '6/10/17 8:36 PM' with Gradle 2.14.1
 *
 * @author pdoshi, @date 6/10/17 8:36 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
